# Generated by Django 6.1.1 on 2026-09-08 17:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, help_text='Ex: +237 670000000', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, help_text='Ex: DRV-012', max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Moto', 'Moto (Benskin)'), ('Small Truck', 'Small Truck'), ('Pickup', 'Pickup'), ('Van', 'Delivery Van')], default='Moto', max_length=30)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('current_neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home Goods', 'Home Goods'), ('Groceries', 'Groceries'), ('Beauty', 'Beauty'), ('Phones & Accessories', 'Phones & Accessories')], db_index=True, max_length=50)),
                ('unit_price_fcfa', models.PositiveIntegerField(help_text='Unit price in FCFA (no decimals)')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Douala', max_length=60)),
                ('neighborhood', models.CharField(db_index=True, help_text='Ex: Akwa, Bastos, Mendong, Bonapriso', max_length=100)),
                ('landmark_reference', models.TextField(help_text='Detailed landmark description: e.g. Face pharmacie du carrefour')),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='logistics.customer')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, help_text='Ex: ECM-00042', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PAID', 'Payée'), ('PROCESSING', 'En préparation'), ('ASSIGNED_TO_DRIVER', 'Assignée au livreur'), ('IN_TRANSIT', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('RETURNED', 'Retournée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('payment_method', models.CharField(choices=[('MTN MoMo', 'MTN Mobile Money'), ('Orange Money', 'Orange Money'), ('Cash on Delivery', 'Cash on Delivery (COD)')], db_index=True, default='MTN MoMo', max_length=30)),
                ('payment_status', models.CharField(choices=[('Pending', 'En attente'), ('Paid', 'Payé'), ('Failed', 'Échoué')], db_index=True, default='Pending', max_length=20)),
                ('total_amount_fcfa', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=5.0)),
                ('delivery_duration_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.customer')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.address')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='logistics.deliverydriver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='logistics.order')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MTN MoMo', 'MTN Mobile Money'), ('Orange Money', 'Orange Money'), ('Cash on Delivery', 'Cash on Delivery (COD)')], max_length=30)),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Hash or unique key from provider to enforce idempotency', max_length=150, unique=True)),
                ('amount_fcfa', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Paid', 'Payé'), ('Failed', 'Échoué')], default='Pending', max_length=20)),
                ('signature_verified', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='logistics.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_fcfa', models.PositiveIntegerField()),
                ('subtotal_fcfa', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'neighborhood'], name='logistics_a_city_ed63ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='idx_order_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'created_at'], name='idx_order_pay_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'status'], name='idx_order_driver_status'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status'], name='logistics_p_provide_b1fdd0_idx'),
        ),
    ]
